### ISSUE TITLE
Lua Errors with toggle settings

### ISSUE THREAD

**Issue by Kimshoui** [GoldpawsStuff/AzeriteUI#86] opened 2021-03-27 20:51 UTC
## The problem  

Hi, I have a ton of Lua Errors, and this is the first of the series ! I begin with this one, because it's the most frequent and the most reproductible one.

It happens when I try to change some aspects of the UI. When I toggle some settings (listed in "Steps to Reproduce" category), it seems to work, but in the menu, the settings don't toggle (from red to green) and the Lua Error appears.

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [ ] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [X] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

Here is the Lua Error (for one of the settings) : 

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedFrames.lua:659: attempt to call field 'Enable' (a nil value)
Time: Sat Mar 27 21:22:49 2021
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedFrames.lua:659: attempt to call field 'Enable' (a nil value)
[string "=[C]"]: ?
[string "@Interface\FrameXML\RestrictedExecution.lua"]:431: in function <Interface\FrameXML\RestrictedExecution.lua:420>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:91: in function `SecureHandler_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = "Call failed: Interface\FrameXML\RestrictedFrames.lua:659: attempt to call field 'Enable' (a nil value)"

And here is a screenshot of what happens on my screen : 

![image](https://user-images.githubusercontent.com/63460018/112733907-01295980-8f43-11eb-8815-4f7a89bd6b46.png)

Also, here is what the debug console displays (it continues with a lot of entries but I don't know how to expand the console and didn't wanted to spam screenshots ^^) : 
![image](https://user-images.githubusercontent.com/63460018/112734123-2ff3ff80-8f44-11eb-8fc7-859489ff4146.png)

### Steps to reproduce  

I just have to toggle one of these settings and the error appears (I have the french traduction of the game, so I'm sorry if these trads are not the exact terms ^^) : 

Exploration Mode > Hide Player Overlay (The one used for the error message I sent) 
Exploration Mode > Chat Positioning
Nameplates > PRD > Activate
Nameplates > PRD > Show Always
Nameplates > PRD > Show in Combat
Nameplates > PRD > Show with Target
Action Bars > Pet Bar > Activate
Action Bars > More Buttons
Action Bars > No +
Action Bars > +5
Action Bars > +11
Action Bars > +17

As you can see, it seems to only affects settings that are conditions to other settings

I noticed the same kind of error when I toggle the "Bigger Bars" (something like that, again, I have the french version of the game) in the Blizzard's Menu > Interface > Names pannel for PRD settings (I know I shouldn't touch these settings with AzeriteUI enable, but my Nameplates stoped working yesterday and I had to try something in here ^^ The problem is solve since then, but I tried to see if this error still came out and it did)

### Expected behaviour  

The toggled setting should be applied to the UI, change color (Red or Green) and it's related settings should be grayed out and vice versa)

### Actual behaviour  

The toggled setting seems to be applied in most case, but that's all and the Lua Error panel appears in the middle of the screen and I have to reload the UI

That's all ! Thanks in advance :D

**Comment by goldpaw** [comment] 2021-03-27 21:01
Hi again, and thanks for the report! 

Yes, I'm actually aware of the enable-bug-thingie. Seem to happen a lot with actionbar settings, when changing number of buttons. Didn't use to bug out, it got added the last week, so I've got some debugging to do.

What I wasn't aware of, or hadn't discovered yet, is the connection to other settings. Good catch, that'll definitely make the bug tracking easier! :)

As for the output in my console, that is unrelated, and isn't causing bugs. It's just a notice to myself that the localization for those mentioned texts doesn't exist. And that, I was totally unaware of. So thanks again, heh. Guess I got to get that fixed too! :)

**Comment by Kimshoui** [comment] 2021-03-27 21:08
Oh ! I'm really glad that it helped ! It's clearly not a annoying bug because it happens only when toggling something and when the UI is configured it's done ^^

But is there anything related with colours in any way ? Because the other major Lua Errors that I got happens randomly in dungeons and mention a color issue in the log... I don't know if I should do an other bug report for this... It seems to be a clearly different issue though ^^

**Comment by goldpaw** [comment] 2021-03-27 21:29
The color bug was the one I knew about and fixed. It should be fixed, at least?

**Comment by Kimshoui** [comment] 2021-03-28 04:07
In the 459 with the raid fixes ?

I tested it in dungeon on the 460 and had the error :/
I didn't test on the 462 though, I'll do it tomorrow ^^

Should a do a ticket if it still occurs ?

**Comment by goldpaw** [comment] 2021-03-28 07:58
If it occurs, yes please. The bug output alone could tell me where it is. 

Back to the Enable/Disable bug in the restriced environment. I have found the place the problem is. It's Blizzard that fucked it up in 9.0.5.

They rewrote part of their restricted environment that handles secure clickable frames, meaning frames that can be clicked in combat and still hide or show other secure frames like actionbuttons and unitframes. Normal frames can't do that. 

I can work around it, but I'm going to tell Blizzard about this first. Was no place to report it in any forums, they just don't seem to have any interface forums anymore. So I tweeted it to them! 

https://twitter.com/GoldpawsStuff/status/1376080577355464706

I could write workarounds, but I want to see their reply first. Not going to spend hours fixing something on their end, if they can fix it instead.

**Comment by goldpaw** [comment] 2021-03-28 09:15
New update: I wrote the workaround anyway. Can't wait for Blizzard, we need our menu! 

Wrote a system that checks for WoW client version, and uses my fix only if we have a bugged WoW version or more recent. Going to check it for the classic version, then release the fix! :)

**Comment by goldpaw** [comment] 2021-03-28 10:09
The locale bugs were just messages reporting that the frFR locale was missing the entries, but the default locale was used instead. I reworked that part a tiny bit, and the messages now better indicate what is actually happening.

And changing actionbars in combat is working fine with my workaround. A bit more testing and I'm uploading it. Yay! 

![WoWScrnShot_032821_120331](https://user-images.githubusercontent.com/6476535/112748766-58b8db00-8fbe-11eb-9ba7-dc53e63445d0.jpg)

![WoWScrnShot_032821_120500](https://user-images.githubusercontent.com/6476535/112748769-5bb3cb80-8fbe-11eb-96b8-3b3c60b6abb3.jpg)

![WoWScrnShot_032821_120502](https://user-images.githubusercontent.com/6476535/112748770-5f475280-8fbe-11eb-9596-3272fafda182.jpg)

**Comment by goldpaw** [comment] 2021-03-28 14:22
Menu fixed in 3.2.463-RC. Should be out any second.

**Closed by goldpaw** 2021-03-28 14:22 UTC
Labels: bug
