### ISSUE TITLE
Can't remove Buff by right clicking on them on the buff bar

### ISSUE THREAD

**Issue by Kaybris** [GoldpawsStuff/AzeriteUI#9] opened 2022-11-30 00:04 UTC
Can no longer turn off/remove buffs by right clicking on the icon on the buff bar.

**Comment by anaarkei** [comment] 2022-11-30 06:03
Can confirm, this is happening to me too.

**Comment by Goldpaw** [comment] 2022-12-08 07:54
not a bug, it's intentional. buffs could never be removed from the filtered buff bar in combat anyway, only out of combat. 

I'm going to be adding a full, unfiltered buff display, that can be toggled. similar to what we see in the default UI right next to the minimap. And there everything can be removed. No ETA on this, but "one of these days in the very near future" is a good guess. I'll be adding all the missing parts as well as a menu, option to toggle modules, more movable frames and all. 

Closing this one as it's not a bug, but actually working as intended!

**Closed by Goldpaw** 2022-12-08 07:54 UTC

**Comment by qq5570461** [comment] 2022-12-08 08:14
actually buffs could not be removed from the filtered buff bar out of combat，4.0.16

**Comment by Goldpaw** [comment] 2022-12-08 08:40
yes, I worded that poorly. let me redo it: 

buffs could never be removed from the filtered buff bar **in the old AzeriteUI3** in combat anyway, only out of combat. 

it was never intended to be available at all in azeriteui4. the aforementioned upcoming full buff display will be for that. up to that, macros and chat commands to `/cancelaura nameofaura` is the way to go.
