### ISSUE TITLE
9.2.5 lua error

### ISSUE THREAD

**Issue by xuesemofa** [GoldpawsStuff/AzeriteUI#146] opened 2022-08-09 14:15 UTC
Game version: retail 
           The 3.2.547-rc version released on August 9 appeared many Lua errors after entering the game,By deleting other plug-ins, the test results of this plug-in are kept separately,No problem occurs after returning to 3.2.546-rc；
(Grammar from translation software may not be easy to understand, please forgive me)

**Comment by xuesemofa** [comment] 2022-08-10 11:08
Game version: retail
3.2.548-RC
Message: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:398: FriendsTooltip doesn't have a "OnTooltipSetSpell" script
Time: Wed Aug 10 19:06:49 2022
Count: 1
Stack: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:398: FriendsTooltip doesn't have a "OnTooltipSetSpell" script
[string "=[C]"]: in function `HookScript'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:398: in function `SetBackdrop'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:342: in function `Style'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:853: in function `StyleTooltips'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:948: in function `OnEnable'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:282: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:737: in function `ForAll'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:252: in function `Init'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:867: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: (*temporary) = FriendsTooltip {
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:203
 NineSlice = <unnamed> {
 }
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:172
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:191
 0 = <userdata>
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:199
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:187
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:195
}
(*temporary) = "OnTooltipSetSpell"
(*temporary) = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua:376

**Comment by Goldpaw** [comment] 2022-08-10 11:15
But have you tried 3.2.548-RC which I uploaded an hour ago? It should fix most of the tooltip bugs that got introduced yesterday!
https://www.curseforge.com/wow/addons/azeriteui/files

**Comment by Goldpaw** [comment] 2022-08-10 11:16
It is new that "OnTooltipSetSpell" doesn't exist on FriendsTooltip, though. Never seen that bug before, but I'm going to hopefully assume that is just a result of the other bugs that got fixed(?).

**Comment by Goldpaw** [comment] 2022-08-10 11:19
Going to assume this might be a duplicate of the same issue as in #147

**Comment by Goldpaw** [comment] 2022-08-10 11:29
Added checks to see if the script handlers are supported on each tooltip in 3.2.549-RC, which should be available shortly on the webpages and in the apps a little later.

**Closed by Goldpaw** 2022-08-10 11:29 UTC
Labels: bug, duplicate
