### ISSUE TITLE
Error when depositing Anima again

### ISSUE THREAD

**Issue by Hexus-Proud** [GoldpawsStuff/AzeriteUI#64] opened 2020-12-26 15:19 UTC
### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x ] Retail 
	- [ ] Battle for Azeroth
	- [ x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [x ] Retail 

### What addon theme(s) does it happen in?  

- [ x] Azerite 
- [ x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [ x] Yes 
- [ x] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [x ] Warrior 

### Actual behaviour  

I wonder why the BUG is closed as done. I still have the problem. With both themes. I guess it doesn't matter what pact you have, because I'm with the Venthyr. I've tried it with and without other addons, always the same error. I hope you look at the problem again. Thank you.

Message: ...ScriptedAnimations\ScriptAnimatedModelSceneActor.lua:71: attempt to perform arithmetic on local 'sourceX' (a nil value)
Time: Sat Dec 26 16:14:26 2020
Count: 1
Stack: ...ScriptedAnimations\ScriptAnimatedModelSceneActor.lua:71: attempt to perform arithmetic on local 'sourceX' (a nil value)
[string "@Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua"]:50: in function `StartEffect'
[string "@Interface\SharedXML\ScriptedAnimations\ScriptAnimatedModelScene.lua"]:151: in function `action'
[string "@Interface\SharedXML\ScriptedAnimations\ScriptAnimatedModelScene.lua"]:87: in function `ExecuteOrDelayUntilSceneSet'
[string "@Interface\SharedXML\ScriptedAnimations\ScriptAnimatedModelScene.lua"]:154: in function `AddEffect'
[string "@Interface\AddOns\Blizzard_CovenantSanctum\Blizzard_CovenantSanctumUpgrades.lua"]:212: in function `OnAnimaGained'
[string "@Interface\AddOns\Blizzard_CovenantSanctum\Blizzard_CovenantSanctumUpgrades.lua"]:165: in function <...CovenantSanctum\Blizzard_CovenantSanctumUpgrades.lua:160>

Locals: self = <table> {
 CancelLoopingSound = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:107
 GetInitialEffectID = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:28
 BeginBehavior = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:208
 CancelEffect = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:180
 soundEnabled = true
 effectStarted = true
 activeBehaviors = <table> {
 }
 effectCount = 1
 FinishLoopingSound = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:113
 RunEffectFinish = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:159
 SetSoundEnabled = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:36
 target = <unnamed> {
 }
 effectID = 107
 UpdateActorDynamicOffsets = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:174
 initialEffectID = 107
 GetCurrentEffectID = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:24
 source = CharacterBag1Slot {
 }
 Init = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:4
 CheckResolution = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:147
 onEffectResolution = <function> defined @Interface\SharedXML\FunctionUtil.lua:38
 IsActive = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:103
 InternalCancelEffect = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:184
 IsSoundEnabled = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:32
 GetEffect = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:20
 FinishEffect = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:119
 DeltaUpdate = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:76
 RunEffectResolution = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:153
 modelScene = GlobalFXDialogModelScene {
 }
 StartEffect = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:40
 SetDynamicOffsets = <function> defined @Interface\SharedXML\ScriptedAnimations\ScriptAnimatedEffectController.lua:167
}

**Comment by goldpaw** [comment] 2020-12-29 08:13
It's marked as "done" because I did both verify it, reproduce it, and fix it, and has personally never seen it since. I wouldn't close a bug report or change its status if anything else was the case. So please don't immediately assume this is the same error originating from the same place, and please refrain from comments such as "I wonder why the BUG is closed as done. I still have the problem."

Anyway, the bug report is a little unclear. Does it happen with AzeriteUI being the only enabled addon or not? You clicked both yes and no. That's not possible! :smile: 

It is vital to figuring out the bug, as if it does NOT happen when this is the only enabled addon, chances are it's another addon or a conflict causing it. Beacuse the bug report itself does not indicate this UI, it only lists blizzard code.

**Comment by Hexus-Proud** [comment] 2020-12-29 14:38
Sorry i thought this is the same problem. I tried all addons in both versions (azerite / legacy). Once with all addons and then only the azerite ui. The error code came every time. Then i tested all addons without azerite ui, no error message and when i issued all addons there was no error message, too. I have already completely deleted and reinstalled the azerite ui, strangely enough the addon list always says ... beta. Is that correct or was something incorrectly deleted?

**Comment by Hexus-Proud** [comment] 2020-12-29 15:00
Maybe the German account is the problem?
I'll test the new update in detail this evening. I hope that I can narrow down the problem even more. Thank you...

I once made a small donation on paypal. I hope there will be enough beers. I know it's a bit more expensive with you than with us ... jubel

**Comment by goldpaw** [comment] 2020-12-29 15:16
"Small" donation, lol! Thanks a thousand! And that's not what I call "small"! Safe to say I'm celebrating New Year's this year! :smile: :heart: :beers: 

Anyhow, back to the bug! My suspicion here is that even though I fixed the original bug, the thing that caused it might be caused by other things too. So I'll be looking into what I did when fixing the (almost) identical bug, and see if I can somehow safe-guard it to just fix ALL situations where this can happen! 

I'm speaking fairly vaguely and unspecific here, which is ofc because I don't know where this bug is coming from. I will try to reproduce it, and I'll particularly try to reproduce it on both my level 55 warrior, and a much lower level warrior that hasn't gotten any azerite powered items yet. Because I have a feeling this has something to do with having or not having an azerite powered item. 

I will update this thread when I know something more! 

And no, I don't think the game client language has anything to do with this. It shouldn't have. The bug occurs in plugins handling azerite power. Numbers. Not names.

**Comment by Hexus-Proud** [comment] 2021-01-07 00:57
So, I have the same error with my Demon Hunter by the Bastions...?????

**Comment by Hexus-Proud** [comment] 2021-01-15 00:11
I have a new error with my Shaman

Message: ...ScriptedAnimations\ScriptAnimatedModelSceneActor.lua:71: attempt to perform arithmetic on local 'sourceX' (a nil value)
Time: Fri Jan 15 01:05:18 2021
Count: 1
Stack: ...ScriptedAnimations\ScriptAnimatedModelSceneActor.lua:71: attempt to perform arithmetic on local 'sourceX' (a nil value)

Locals: 

And I have no azerite power items with me....

**Comment by goldpaw** [comment] 2021-04-26 04:55
I see I never commented again here. But is it still happening? I would actually expect not.
 
The error seemed to have been related to updating tracked currencies on the bacpack, and how AzeriteUI attaches the bag buttons to the bottom of the backpack. This caused those buttons to not have a position for a little while (the missing 'sourceX'), and thus the error. I added a workaround for this some months back.

**Closed by goldpaw** 2021-04-26 04:55 UTC
Labels: bug, question
