### ISSUE TITLE
Area Action being movable, or creator moving to new location

### ISSUE THREAD

**Issue by tchk0ma** [GoldpawsStuff/AzeriteUI#29] opened 2020-09-25 11:12 UTC
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [X] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
The Area Action hotbar button posted in the middle of the screen is kind of annoying.

**Describe the solution you'd like**
I would either like to see this button be able to be moved independently, or be moved to a new location permanently by creator. 

**Describe alternatives you've considered**
I have not found a way to remove it altogether. I use Bartender4 for a couple more hotbars, but no such luck finding a way to move that Area Action button.

**Additional context**
https://imgur.com/a/0DE9hT7
Screenshot of my UI with edit feature in Bartender4 and AzeriteUI on.

**Comment by goldpaw** [comment] 2020-11-30 16:55
This was a duplicate of another issue, and also solved. I have since this moved both the zone ability and extra action button frame, so they shouldn't be right in the middle of the screen in any theme anymore. :)

**Closed by goldpaw** 2020-11-30 16:55 UTC
Labels: enhancement
