### ISSUE TITLE
retail 9.2.5.44908 tooltip erros

### ISSUE THREAD

**Issue by Antunes43** [GoldpawsStuff/AzeriteUI#148] opened 2022-08-09 23:32 UTC
## The problem
AzeriteUi not loading properly on the retail version, with the blizzardUI being loaded on top of azeriteUI and generating a bunch of errors. This error does not happen on the previous version of azeriteUI(3.2.546-RC)

### Did you update to the most recent version?
- [ ✅ ] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ✅] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [ ] Shadowlands (Retail)
- Alpha/Beta
  - [ ] Wrath of the Lich King
  - [ ] Dragonflight

### What addon theme(s) does it happen in?

- [ ✅] Azerite
- [ ✅] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [✅ ] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [ ] Yes
- [ ✅] No

### What classes does it happen on?

- [ ] Death Knight
- [✅ ] Demon Hunter
- [ ✅] Druid
- [ ] Evoker
- [✅ ] Hunter
- [ ] Mage
- [✅ ] Monk
- [ ✅] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ ] Warlock
- [ ] Warrior

### Any logs, screenshots, error output, etc?
https://pst.klgrth.io/paste/3baxh
![image](https://user-images.githubusercontent.com/29907925/183778744-a581b3b5-939d-4f10-b30f-3a7a4966f3f8.png)

### Steps to reproduce

just loading the game generates the error.

### Expected behavior
BlizzardUi should not be shown and no errors should arise from the simple loading of the game

### Actual behavior
Errors and blizzardUi being above the beloved azeriteUI

**Comment by Goldpaw** [comment] 2022-08-10 10:07
Duplicate of #147

**Closed** 2022-08-10 10:07 UTC
Labels: bug
