### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by flowowbg** [GoldpawsStuff/AzeriteUI#151] opened 2022-08-10 09:00 UTC
### Did you update to the most recent version?
- [x] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [x] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [ ] Shadowlands (Retail)
- Alpha/Beta
  - [ ] Wrath of the Lich King
  - [ ] Dragonflight

### What addon theme(s) does it happen in?

- [x] Azerite
- [ ] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [x] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [ ] Yes
- [x] No

### What classes does it happen on?

- [x] Death Knight
- [x] Demon Hunter
- [x] Druid
- [ ] Evoker
- [x] Hunter
- [x] Mage
- [x] Monk
- [x] Paladin
- [x] Priest
- [x] Rogue
- [x] Shaman
- [x] Warlock
- [x] Warrior

**Comment by flowowbg** [comment] 2022-08-10 09:05
![help](https://user-images.githubusercontent.com/42470115/183861861-6eac509d-5eb6-4155-ae03-a0b1246a1ed6.jpg)

**Comment by Goldpaw** [comment] 2022-08-10 10:09
Duplicate of #147

**Closed by Goldpaw** 2022-08-10 10:09 UTC
Labels: bug, duplicate
