### ISSUE TITLE
LUA Errors when logging in/bars not loading

### ISSUE THREAD

**Issue by waynemolina** [GoldpawsStuff/AzeriteUI#124] opened 2021-11-14 15:31 UTC
## The problem  

Receive LUA error after a fresh install when logging in.  Player bars appear but action bars do not and remain the default Blizzard bars.

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [X] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [X] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [X] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

Receive this error upon logging in:
```
Message: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:833: hooksecurefunc(): GameTooltip_SetBackdropStyle is not a function
Time: Sun Nov 14 10:24:41 2021
Count: 1
Stack: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:833: hooksecurefunc(): GameTooltip_SetBackdropStyle is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:833: in function `SetTooltipHooks'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:918: in function `OnEnable'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:282: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:737: in function `ForAll'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:252: in function `Init'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:867: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: 
```

Receive these errors in addition to the first after a /reload
```
Message: Interface_Vanilla\FrameXML\MultiActionBars.lua:87: MultiBarRight:SetScale(): Scale must be > 0
Time: Sun Nov 14 10:26:46 2021
Count: 1
Stack: Interface_Vanilla\FrameXML\MultiActionBars.lua:87: MultiBarRight:SetScale(): Scale must be > 0
[string "=[C]"]: in function `SetScale'
[string "@Interface_Vanilla\FrameXML\MultiActionBars.lua"]:87: in function `MultiActionBar_Update'
[string "@Interface_Vanilla\FrameXML\InterfaceOptionsPanels.lua"]:1176: in function `InterfaceOptions_UpdateMultiActionBars'
[string "*:OnLoad"]:4: in function `setFunc'
[string "@Interface_Vanilla\FrameXML\InterfaceOptionsPanels.lua"]:1146: in function <...nterface_Vanilla\FrameXML\InterfaceOptionsPanels.lua:1139>

Locals: (*temporary) = MultiBarRight {
 0 = <userdata>
 slideOut = <unnamed> {
 }
}
(*temporary) = -0.020642
```
```
Message: Interface_Vanilla\FrameXML\MultiActionBars.lua:87: MultiBarRight:SetScale(): Scale must be > 0
Time: Sun Nov 14 10:26:46 2021
Count: 1
Stack: Interface_Vanilla\FrameXML\MultiActionBars.lua:87: MultiBarRight:SetScale(): Scale must be > 0
[string "=[C]"]: in function `SetScale'
[string "@Interface_Vanilla\FrameXML\MultiActionBars.lua"]:87: in function `MultiActionBar_Update'
[string "@Interface_Vanilla\FrameXML\ActionBarController.lua"]:138: in function `ValidateActionBarTransition'
[string "@Interface_Vanilla\FrameXML\ActionBarController.lua"]:106: in function `ActionBarController_UpdateAll'
[string "@Interface_Vanilla\FrameXML\ActionBarController.lua"]:37: in function <Interface_Vanilla\FrameXML\ActionBarController.lua:34>

Locals: (*temporary) = MultiBarRight {
 0 = <userdata>
 slideOut = <unnamed> {
 }
}
(*temporary) = -0.020642
```

### Steps to reproduce  

Fresh install of AzeriteUI 3.2.515-Release-classic from WoWUp

### Expected behaviour  

No LUA errors; action bars should not be the default

### Actual behaviour  

LUA errors on logging in and action bars are not styled

**Comment by goldpaw** [comment] 2021-11-15 11:06
This is a duplicate of #123, actually. It's the same bug from the same codebase.

**Closed by goldpaw** 2021-11-15 11:06 UTC
Labels: bug
