### ISSUE TITLE
Not loaded at all

### ISSUE THREAD

**Issue by JasonQWJ** [GoldpawsStuff/AzeriteUI#14] opened 2020-08-13 00:24 UTC
### Error1 
    Message: ...face\AddOns\AzeriteUI\back-end\libraries\minimap.lua:427: attempt to index global 'ObjectiveTrackerFrame' (a nil 
    value)
    Time: Thu Aug 13 08:17:49 2020
    Count: 1
    Stack: ...face\AddOns\AzeriteUI\back-end\libraries\minimap.lua:427: attempt to index global 'ObjectiveTrackerFrame' (a nil value)
    ...face\AddOns\AzeriteUI\back-end\libraries\minimap.lua:427: in function `SyncMinimap'
    ...face\AddOns\AzeriteUI\front-end\blizzard\minimap.lua:746: in function `SetUpMinimap'
    ...face\AddOns\AzeriteUI\front-end\blizzard\minimap.lua:1571: in function `OnInit'
    ...rface\AddOns\AzeriteUI\back-end\libraries\module.lua:233: in function `Init'
    ...rface\AddOns\AzeriteUI\back-end\libraries\module.lua:263: in function `?'
    ...rface\AddOns\AzeriteUI\back-end\libraries\module.lua:690: in function `ForAll'
    ...rface\AddOns\AzeriteUI\back-end\libraries\module.lua:247: in function `Init'
    ...rface\AddOns\AzeriteUI\back-end\libraries\module.lua:813: in function `?'
    ...face\AddOns\AzeriteUI\back-end\libraries\message.lua:63: in function `Fire'
    ...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

    Locals: self = <table> {
     SetBlizzardTooltipBackdrop = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2558
     ForAll = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:678
     IsRetail = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\clientbuild.lua:69
     SetBlizzardTooltipBackdropOffsets = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2547
     modules = <table> {
     }
     GetServerTime = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\time.lua:76
     ForAllBlizzardTooltips = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2622
     ShowMinimapTrackingMenu = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\minimap.lua:798
     SetDefaultTooltipStatusBarSpacing = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2410
     SetMinimapCompassRadius = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\minimap.lua:1064
     layout = <table> {
     }
     NewConfig = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\db.lua:137
     KillBlizzardTooltipBackdrop = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2536
     PlaySoundKitID = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\sound.lua:322
     SetDefaultTooltipPosition = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2333
     PurgeSavedSettingFromAllProfiles = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\db.lua:170
     IsUnitLevelAtEffectiveExpansionMaxLevel = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\playerdata.lua:145
     GetCurrentClientBuild = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\clientbuild.lua:90
     SetMinimapCompassTextFontObject = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\minimap.lua:1102
     SetDefaultTooltipBackdropOffset = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2374
     SetDefaultTooltipStatusBarTexture = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2422
     IsInitialized = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:713
     SetUpMBB = <function> defined @Interface\AddOns\AzeriteUI\front-end\blizzard\minimap.lua:1190
     SetDefaultTooltipStatusBarInset = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2383
     SetDefaultTooltipBackdropBorderColor = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2365
     SetDefaultTooltipStatusBarOffset = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2391
     RegisterUnitEvent = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:104
     CreateTooltip = <

### Error2

    Message: ...ace\AddOns\AzeriteUI\front-end\custom\actionbars.lua:1381: bad argument #1 to 'pairs' (table expected, got nil)
    Time: Thu Aug 13 08:17:50 2020
    Count: 1
    Stack: ...ace\AddOns\AzeriteUI\front-end\custom\actionbars.lua:1381: bad argument #1 to 'pairs' (table expected, got nil)
    [C]: ?
    ...ace\AddOns\AzeriteUI\front-end\custom\actionbars.lua:1381: in function `GetSecureUpdater'
    Interface\AddOns\AzeriteUI\front-end\custom\menu.lua:784: in function <Interface\AddOns\AzeriteUI\front-end\custom\menu.lua:779>
    Interface\AddOns\AzeriteUI\front-end\custom\menu.lua:804: in function `?'
    ...face\AddOns\AzeriteUI\back-end\libraries\message.lua:63: in function `Fire'
    ...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

    Locals: (*temporary) = nil
    (*temporary) = "table expected, got nil"
     = <function> defined =[C]:-1

**Comment by goldpaw** [comment] 2020-08-13 08:23
Well I can't reproduce it, but I can see what's happening. For some reason the Blizzard built-in ObjectiveTracker addon is loaded after our UI for you. For me it's always loaded before. 

But I'll add in a workaround, and upload the fix ASAP! :)

**Comment by goldpaw** [comment] 2020-08-13 08:41
Fixed in 2.0.390-RC.

**Closed by goldpaw** 2020-08-13 08:41 UTC
Labels: bug
